yaruo1 = '''
　 　＿＿＿_
　　　／　　 　 　＼
　 ／─　 　 ─　　＼
／ （●） 　（●）　　　＼
|　 　 （__人__）　　　　　 |
＼　　 ⊂ ヽ∩　　　　 <
　 |　 |　 '､＿ ＼　／　 )
　 |　 |＿＿＼　 “　 ／
　　＼ ＿＿＿＼_／
'''

yaruo1_ ='''
　　　＿＿＿_
　　　／　　 　 　＼
　 ／　　─　 　 ─＼
／ 　　 （●） 　（●） ＼
|　 　　 　 （__人__）　 　 |
./　　　　 ∩ノ ⊃　　／
(　 ＼　／ ＿ノ　|　 |
.＼　“　　／＿＿|　 |
　　＼ ／＿＿＿ ／
'''

yaruo_aori1= '''
　　　 　 　 ＿＿__
　　 　　 　 ／_ノ 　ヽ＼
　　 　 　／ （ ●）　（●）、
　　　 ／::::::::⌒（__人__）⌒＼
　　　 |　　 　　　|r┬-|　　　 |
　　　 ＼ 　 　 　 `ー'´　　／
⊂⌒ヽ　〉　　　 　　　 ＜´/⌒つ
　 ＼　ヽ　 /　　 　 　 　 ヽ　/
　　　＼_,,ノ　　　　　　|､＿ノ
'''

yaruo_yubisashi='''
　　　　＿＿＿_
　　　　 ／　　　　　＼
　　　／　＼:::::::::::／　＼
　 ／　　（●）:::::（●）　　＼
　 |　 　　　（__人__）　u　　　|
　　＼　　.　|┬-r|　　　　／
　　 ／　　　｀ー´９ｍー　）
　　　　　　　　　　`ーー‐'ﾞ
'''

yaruo_aori2='''
　　　　　　　　　＿＿＿
　　　　　　 　 　 ／⌒　ー､＼
　　　 　 　 　 ／（ ●） 　（●）＼
.　　　　　　／::::::⌒（__人__）⌒::::::＼
　 ｃー､ 　 |　　　 　|r┬-/ ' 　 　 　|⌒,一っ
　,へ　λ　＼　　　 `ー‐' 　 　　 ／　入　 へ、
<<<／ヽ　 　 　 　　 　 　　　　　 　 　　/＼>>>
'''

yaruo_joy='''
　　 ＿＿＿_
　　　／⌒　　⌒＼
　 ／（ ●） 　（●）＼
／::::::⌒（__人__）⌒:::::＼
|　　　　　|r┬-|　　　　 |
＼ 　　 　 `ー'´ 　 　 ／
'''

yaruo_anger="""
　　　　　　　　　　　∩＿
　　　　　　　　　　　　　〈〈〈　ヽ
　　　　 ＿＿＿_.　　　〈⊃　　}
　　　／　　 　 　＼　 　 |　　 |
　 ／　ヽ、　 　_ノ　＼　 !　　 !
／ 　 （●） 　（●） 　 ＼|　　 l
|　 U 　 （__人__）　　　　 .| 　／
＼　　　　|i||||||i|　　 　 ／／
　/　＿＿｀ ー' 　 　 　 /
　(＿＿＿）　　　　　　/
"""

yaruo_anger2="""
　　　　 ＿＿＿
　　　　 ／＼　 ／ ＼
　　　／（●）　（●.） ＼
　 ／ 　　（__人__） 　 　 ＼
　 |　　　 　 |::::::|　　ノ（　　|
　 ＼　　 　 l;;;;;;l　　 ⌒ ,／
 　 ／ヽ　 　`ｰ´ 　 ｨ⌒ヽ
 　 rｰ'ゝ　　　　　　　〆ヽ .)
　ﾉヾ　,>　　　　　　ヾ_ノ,ヽ}
　ヽ ヽ|　　　　　　　　ヽ_ノ
"""

yaruo_anger3="""
　　　　　  　_＿＿＿┘(
　　　　　　　 ／＼　 ／　⌒
　　　　 　 ／（○）　（○.） ＼
　　　　 ／ 　　（__人__） 　 　 ＼
　　　　 |　　　 　 |::::::|　　　 　　|
　　　! |!l＼　　　 l;;;;;;l 　 　　,／
　　　　　i| ／　　 　ｰ´　　　　＼
　　　 i／　l!　　　　　　　　　　 ＼
 　 そ|彡∪ 　 　 　 　 　 , --、 　）
　 ∑ !彡,l　<　　　 　 　 ( 　 ＿／
　　 ﾚY^Ｖ^ヽｌ.　　　　　　 ￣
"""

yaruo_anger_max="""
　　　　　　　　　　　　　(⌒ヾ｀
　　　　　　　　　　　　 ゝ´　,）)
　　　　　　　 (（ ⌒ゝ 　 lij
　　　　　　　　　 ｰ" ミ
　　　　　　 ／/_/l　　 ＿＿＿_
　　　　　　 |　 __/　／　 ノ（ 　＼
　　　　　／ ／　／_ノ三ヽ､　　　＼
　　 γ⌒ヽ'　 ／（ ｡ ）三（ ﾟ ）　=ll=.＼　 γ⌒ヽ
　　 入__ ノ＼.|　　（__人__）　ノ（ 　 　 |／弋　_ノ
　 ［_Ａ 〉 ヽ　 ＼　 |++++| 　⌒　　 ／　　／
　　　　　　　＼　　　---　　　　　　 　 ／
　　　　　　　　 |　　　　　　　　　　　　|
　　　ｾ⌒ヽ 个　、　　　　　　　　　　/
　 　 l三三　　,　　　　　　　　　　　 /　 ｨニヽ
　　　|三三.レ'＼　　　　　　　　　　レ´ 　 /.ヽ
　　　`ｰ-ｰ'　　　 ヽ_ _＿＿　　 　 　 　 イ爻..|
　　　　　　　　　　　　　　　　＼＿＿／.弋＿ﾉ
"""

yaruo_cry="""
　　　　　 ＿＿_＿_
　　　　　　／　ノ'　＾ヽ_＼
　　　ﾟ　／ ｡;'⌒） 　（⌒ヽ＼°
　　　／　o'ﾟ~（___人___）~o°＼゜
　 　 |　　　 ﾟ　|/⌒ヽ| 　ﾟ　　　|
　　　＼　　 　 ｀ ⌒ ´ 　 　 ／
　　 　 ／`　　　　　　　　 ´＼
　 　 /　　 　 　 ｀`"´ 　 　 　 ヽ
　　 .| 　 Ｙ　 　 　 　 　 　 Y 　 |
　　 .|　　|　　　　　　　　　 |　　|
"""

yaruo_sorry="""
　　　　　　＿＿＿_
　　　　　　 ／　　　　　＼
　　　　　／　 _ノ　 ヽ､_　 ＼
　　　 ／　 oﾟ⌒　　　⌒ﾟo　 ＼
 　 　 |　 　 　 （__人__）　　　　 |
　　　 ＼　　 　 ｀ ⌒´　　 　 ／
　　　　　>　　　 /　）ヽ　　 <
　　 　 (　 ＼ ／ __ﾊ　） ／　 )
　　　　 ＼　 ﾞ　 ／ヽ　ﾞ　　／
　 　 　 　 ＼_／　　 ＼_／
"""

yaruo_nayami='''
　 　＿＿＿_
　　　／　　 　 　＼
　 ／　　　_ノ　ヽ､_.＼
／ 　　 （●） 　（●） ＼
|　 　　 　 （__人__）　 　 |
/　　　　 ∩ノ ⊃　　／
(　 ＼　／ ＿ノ　|　 |
.＼　“　　／＿＿|　 |
　　＼ ／＿＿＿ ／
'''

yaruo_nayami2='''
　 　　　＿＿＿_
　　　／　　 　 　＼
　 ／＿､　,,／"　　＼
／ （●）　ﾞ（●）　U　＼
|　 　 （__人__）　　　　　 |
＼　　 ⊂ ヽ∩　　　　 <
　 |　 |　 '､＿ ＼　／　 )
　 |　 |＿＿＼　 “　 ／
　　＼ ＿＿＿＼_／
'''

yaruo_nayami_max="""
　　 _＿＿＿
　　　／　 　 　　＼
　 ／　　 　 　　　　＼
／　　　 　　　　　　　 ＼
| 　 ＿, 　　／　 　 　 　 |
＼（ー⊂ヽ､∩ 　ｕ　 　 ﾉ
　 | 　|　ゝ＿ ＼　／ 　)
　 | 　|＿＿＼　　”　／.
　 ＼ ＿＿＿ ＼ ／
"""
yaruo_not="""
　　　　　　　 　 ＿＿＿_
　　　　　　　　　 ／　　 　 　＼
　　　　　　　　／_ノ　　　ヽ､_　＼
　　　　　　 ／　（●） 　（●）　　 ＼
　　　　　　 | 　 　 （__人__）　　 u 　 |
r､　　　 　r､＼　 　 ｀ ⌒´　　 　 ,／
ヽヾ　三　|:l1　>　　 ー‐　　 　 ヘ
　＼>ヽ/ |｀ ｝　　　　　　　　 　 　 ヽ
　 　ﾍ　lノ `'ｿ　ｲ　 　 　 　 　 　 | 　|
　　　 /´　 / ./ |　　　　　　　　　| 　|
　　　 ＼. ｨ_ノ　.|　　　　　　　　　|　 |
　　　　　　　　　|　　　　　　　　　| 　|
"""

yaruo_not2="""
　　　　 ＿＿＿_
　　　　　／　　 　 　＼
　　　 ／　ヽ、　 　_ノ　＼
　　／ 　 （●） 　（●） 　 ＼　ｎ
　　|　 U 　 （__人__）　　　　l^l.| | /）
　　＼　　　　|i||||||i|　　　／| U ﾚ'/／)
　γ⌒　　 　｀ ー'´　　　　ﾉ　　　 ／
　 i　　j　　　　　 　　　ｒニ 　　　　ﾉ
　 ヽ､ l 　　　　　　　　　 !ヽ､_,__／
"""

yaruo_hanahoji="""
　　 ＿＿＿_
　　　／⌒　　⌒＼ ﾎｼﾞﾎｼﾞ
..　／（ ー） 　（ー）＼
／::::::⌒（__人__）⌒:::::＼
|　　　 ｍj |ー'´　　 　 　|
＼　 〈＿_ﾉ　　　　　　／
..　　ノ　　ﾉ
"""

yaruo_hanahoji2="""
　 　 ／￣￣￣ ＼ 　ﾎｼﾞﾎｼﾞ
　　　 ／　―　　　―　＼
 　 ／ 　 （●） 　（●）　　＼
 　 |　 　　　（__人__） 　　 　 |
 　 ＼　　 ｍj |⌒´ 　　 　／
　　　 　 〈＿_ﾉ
　　　　 ノ 　 ﾉ
"""

yaruo_ushiromuki="""
　 　 　 　 　 　 　　―‐　､
　　　　　　　　 ／　　　　.:ヽ
　　　　　　　／　　 　 　 .:.:.:.:,
　　　　　　　|　　　　　.:.:.:.:.:.:.:}
　　　　　　　＼　 .:.:.:.:.:.:.:.:.:.:ノ
　　　　　　　／　 .:.:.:.:.:.:.:.:.:.:|
　　　　　　(＿　　.:.:.:.:.:.:.:.:.:.:|
　　　　　　| i　!　　 　 .:.:.:.:.:.!
　　　　　 (__ゝ ＿＿＿_,＿ﾉ
　　　　　　　 　 :::::::::::::::::::::::::::
　 　 　 　 　 　 　 ::::::::::::::::::::::::::::
　　　 　 　 　 　 　 　 ::::::::::::::::::::::::::
　　　　 　 　 　 　 　 　 ::::::::::::::::::::::::::
　　　　　　 　 　 　 　 　 　　:::::::::::::::::::::
"""

yaruo_gomakashi="""
　　　 　 　 　 ＿＿__
　　 　　 　 ／ノ　ヽ､_＼
　　 　 　 （●）　（● ）　＼
　　　 ／⌒（__人__）⌒　　 ＼
　　　 |　　　　)　 )　 　 u. 　 |
　　　 ＼　　 `ー'´　 　 　 ／
⊂⌒ヽ　〉　　　 　　　 ＜´/⌒つ
　 ＼　ヽ　 　　 　 　 　 ヽ　/
　　　＼_,,ノ|　　　　　 ､＿ノ
"""


yaruo_aseri="""
　　　　 　 　 ＿＿＿_
　　　　 　 　 ／　　 　 u.＼
　　　　 　 ／ー‐-:::::::::::-‐' ＼
　 　 　 ／ 　 t　 j:::::::ｨ　 ｯ 　 ＼
.　　 　 |. u 　 ｀¨､__,､__,¨´　　　 |
.　　　　＼　 　 　 ｀こ´　　 　 ／
　 　 　 ／　　　 　　　　　u　.＼
"""

yaruo_bareru="""
　　　　　　＿＿＿_
..　　　　／　　　u　＼
　　　／　　／　 　 ＼＼
..　／ 　し （○） 　（○） ＼
　 |　∪　 　 （__人__）　 J |
..　＼　　u　　 ｀⌒´　 　／
"""

yaruo_hansei="""
　　　　 　 ／ ￣￣ ＼
　 　 　 ／ノ　　ヽ__ 　 ＼
　 　 ／（―） 　（― ） 　 ＼
　 　 |.　　（_人＿）　　　u　|
　　　＼ 　 ｀⌒ ´　　 　 ,／
　　 　 / 　　　　　　　　ヽ
.　 　 /　l　　　,/　 /　　 i
　 　 (＿) 　　(__ ノ 　 　 l
　 　 ／　　／　　　___ ,ノ
　 　 !､＿__!､＿_＿＿_つ
"""

yaruo_hirameki='''
　　 　　　　 |
　　 　＼　　__　　／
　　 　＿　（ｍ）　＿
　　 　　　　|ミ|
　　 　 ／ 　｀´　 ＼
　 　　　＿＿＿_
　　　／⌒　　⌒＼　　　　ﾁｰﾝ!
　 ／（ ●） 　（●）＼
／::::::⌒（__人__）⌒::::: ＼
|　　　　　|r┬-|　　　　　|
/　　　　　`ー'´　　　 　 ∩ノ ⊃
(　＼　 　 　 　 　 　 　／＿ノ
.＼　“　　＿＿＿＿ノ　 ／
　　＼_ ＿＿＿＿　　／
'''

yaruo_macho='''
　　　　　　＿＿＿
　　　　　　 ／　　 　 　＼
　　　　　／　─　 　 ─　＼
　　　 ／ 　 （●） 　（●） 　＼
　　　 |　 　 　 （__人__）　　　　|　n,》》)
　　　 ＼　　 　 ｀ ⌒´ 　 　 ／ 　〉 ／
　 ,,,,,　　/⌒ヽ ､　,　　''⌒＼　,／ /
　(巛.,n |　,、　 ￥ 　　λ　 Υ　,/
　 ＼, ''ヽ ,ﾊ,ﾐ,,_人＿.,,ﾉ 'ヽ､. _,ノ
　　　＼_,ｿ　|ﾐ〈ｷ〉彡/
　　　　　　 （ﾐ ヽ,.　/'
　　　　　　 人,　 ）ﾉ
　　　　　／　/　/'
　　　　「’／く　〈、
　　　　し'　　 ＼,,)
'''

yaruo_formal='''
　　　　／￣￣￣＼
　　　　..／ ＿,　、＿. 　＼
　　　／　（● ）　（● ）　 ＼
　　　|　　　 （__人__）　　　　 |
　　　＼　　　｀ ⌒´　　 　 ／
　　 〆~＼　　　　　　　／ヽ
　／:::;;;､:::::::i::ヽ`介´/::::i::::::::::ヽ
<:::::::::::<|:::::::ｌ::::ヽ| | i::::::7;;;;;;:ｌ::::}
. ＼::::::::＼:::::＼;;;i,,/:／:::::::::i:::::{
'''

yaruo_formal_shomen ='''
　　 　 　 ＿＿＿_
　　 　 　 ／　　 　 　＼
　　 　 ／　─　 　 ─　＼
　　 ／ 　 （●） 　（●） 　＼
　　.|　 　 　 （__人__）　　 　 |
　　 ＼　　 　 ｀⌒´　　　 ／
　　 .／＼　　　　　 　 ／ヽ
　　/:::::::::::i::ヽ`介´/::::i::::::::::ヽ
　　{::::r:::::::ｌ::::ヽ| | i::::::7;;;;;;:ｌ::::}
　　}::::|::::::::::＼;;;i,,/:／:::::::::i:::::{
'''

yaruo_formal_joy ='''
　 　　　＿＿＿_
　 　　　／⌒　　⌒＼
　　　／（ ●） 　（●）＼
　 ／　:::⌒（__人__）⌒::::＼
　 |　　　　　|r┬ i 　　　　 |
　 ＼＿＿　`ー‐'　＿＿／
　　/::::::::ﾊ＼/Vヽ/;:i:::::::ヽ
　　| :::r::ｌ::ｌ　　ﾊ　 |:7::::::ｌ::|
'''

yaruo_fight='''
　　＿＿＿
　　 ／＼,,／ 　＼
　／（ ●）（ ●）　＼
　|　　（__人__)　　 　 |
　ヽ　　 ）__丿　　 ／ 　_,=-ｰ-､‘ ・〝 ，
　　 ｀> ´` 　 　 ￣ﾆ三　,r l l l |　☆　∵
　__ /　 　 　 　 /￣￣ヽこ)ＪJJ　〟．`
((k/　 　 　 　 〈
　 /　　,--､　　ヽ
　〈　 〈　　 ヽ　　＼
.....(_＿）...........（_＿_｀)
'''

yaruo_potechi="""
　　　／￣￣￣＼
　　　 ／　⌒ 　 ⌒ 　＼
　　／　 （●） 　（● ）　＼
　　|　　 ⌒（__人__）⌒　　 |
(( 　＼　　 ｡｀,⌒ﾟ:j´　 　／
　　／　／ζ~~~)'　　　　＼　ﾓｸﾞﾓｸﾞ
　　|　 (　^ノ " ")　　　　　 |
　　| ／　/ ｀ー´　　　　 　 |
"""


yaruo_cook="""
　　　　／￣￣＼
　　　　／　⌒　 ⌒ ＼
　　 ／　 （●） 　（●）＼
　　 |　　　 （__人__） 　　 |
　　 ＼　 　　　　　　　／
　　 ／|｀ー‐--‐‐―'|＼
　　/＼|＿＿＿＿＿|| _,ヽ　ｸﾞﾂｸﾞﾂｸﾞﾂ
　　< つ＼　　　　　　,-し､)
―ヽｦ 　＼ニフ　　`-"　――
　　　　[]（("￣｡￣ﾟ￣)）[]
　　　　　| `ー----―"|
"""
yaruo_donatsu="""
 　 　 　 　 　 _＿＿＿
 　 　 　 　 　 ／　　　　　＼
 　 　 　 　 ／ ⌒　　⌒　 　＼
　　　 　 ／ （●）　 （● ）　　 ＼
 　 　 　 |　　ﾞ)（__人__）゛　 ） 　　|
　　　　　＼　　 ｀,､､、　　 　　／
　　　　　／　/⌒)０::）　　 　 ＼
　　　　/　／　/'ﾞ｀'''"　　　　 ､　ヽ
　　　　ゝ､___ノ　　　　　　　　 |　　|
"""

yaruo_seiza='''
　　　　　　　＿＿＿_
　　　　　　　 ／―　―　＼
　　　　　　／（●） 　（●） ＼
　　　　 ／　 　（__人__） 　 　 ＼
　 　 　 |　　　　｀ ⌒´　　 　　　|
　 　　 　＼　　　　 　 　　　　／
　 　 　 　 ／　　　　　　　　　＼
　 　　 　 |　　　・　　　　・ 　 　 ）
.　　　　　|　　|　 　 　 　　 /　 /
　　 　 　 | 　 |　　　　 　 /　 / |
　　 　 　 |　　|　　　 　 /　 / 　|
　 　 　 (YYYヾ　　Y　(YYYヽ　|
　　 　　（_＿＿ノ-'-（'＿＿_）_ﾉ
'''

yaruo2 ='''
　 　 　 ＿＿＿
　　　 　 ／　　　 　 ＼
　　　 ／⌒　　 ⌒　　 ＼
 　 ／（● ）　（● ）　　　ヽ
 　 |　⌒（__人__）⌒　 　 　 |
　　＼ 　 ｀⌒ ´　　　　　／
　    /　　　　 　 　 　 　 ＼
'''

yaranai1 = '''
　　／￣￣＼
　　 ／ _ノ　 ヽ､_ ＼
.　　|　（ ●）（● ）　|
.　　|　　（__人__） 　│
　　 | 　　｀⌒ ´　 　|
.　　 | 　 　 　 　 　 |
.　　 ヽ　　 　　　　/
　　　 ヽ　 　　　 /
　　　　 〉-r:::┬〈、
　　 ／Λ 〉.:〈 7//＼
. ／////V::::::V/////＼
///////∧::://///////}
.////////∨/////////{
'''

yaranai_wink='''
　　／￣￣＼
　　 ／ _ノ　 ヽ､_ ＼
  　.|　 （ ●）（＜）　|
　　|　　（__人__） 　│
　　.| 　　｀⌒ ´　 　|
　　 | 　 　 　 　 　 |
　　 ヽ　　 　　　　/
　　　 ヽ　 　　　 /
　　　　 〉-r:::┬〈、
　　　 /Λ 〉.:〈 7//＼
　　 ////V::::::V/////＼
　 ./////∧::://///////}
　/////// ∨/////////{
'''

yaranai_udekumi='''
　 ／￣￣＼
　　／　　 _ノ　　＼
　　|　　　 （ ●）（●）
　.　|　　　　 （__人__）
　　 |　　　　　｀ ⌒´ﾉ
　.　 |　　　 　∩ ノ ⊃
　 ／ヾ.､_　　ﾉヾ､＿ノ
　(.:::::::＼ ／::::.／ノ:│
　 ＼:::::..“::::／＿|::::::|
　　　＼::／Φ:::::::::::/
　　　　　￣　￣￣
'''

yaranai_atamakakae="""
　　　　　　 （⊃￣￣＼
　　　　　（⊃　　 _ノ　　＼
　　　　（⊃　　 （ ●）（●）
　　　　　|　　　　 （__人__）
　　　　　|　　　　　｀ ⌒´ﾉ
.　　 　 　|　　　　　　 　 }::＼
　　　　 ／ヽ　　　　　　 }:::::::＼
　　　／:::::::::ヽ､＿＿__ノ::::::::::::::）
　 ／::::::::::::::::.ﾍ.:.ﾔ､:::>７|:::＿::/
　|:::::::::::::::::::::::::::ゞ／￣￣（＿)
　 ＼:::::::::::＼　／|　ＪＪＪ　（
　　　＼:::::::／:::::ヾ ､／⊂＿）
"""

yaranai_tukomi="""
　　 ／￣￣＼
　／　　 _ノ　　＼
　|　　　（ ●）（●）
.　|　　　　（__人__）
　 |　　　　 ｀ ⌒´ﾉ
.　 |　　　 　　　　 }
.　 ヽ　　　　　 　 }
　　 ヽ　　　　　ノ　 　 ﾋﾞｼｯ
　　　/:::.ﾍﾔ::ﾌ<_＿_,-ｭ__ 　 て
　 　 |:::::::.ヽi:::.ｿ|:::::::::::li 三） 　（
　 　 |::::::::::::.｀´.:|￣￣ ￣　　 ´
"""

yaranai_choimachi="""
　　　 　 　 　 　 　 　 ／￣￣＼
.　　　　　　　 　 　 ／　ノ　　＼ ＼
.　　　　　　　 　 　 |　 （●）（●）　|
　　　　　　 　 　 　 |　ｕ（__人__）　 |
　 　 　 _ __ 　 　 　 |　　 ｀⌒´　　│
.　　　ｒ( ＼＼r､　　‘，　　　 　 　 ﾉ
　　　 ＼＼＼ヽ}　 　 ヽ　　　＿_/
　　　r─ヽ ` 　 ヽ　　/７只/::'⌒ヽ
　　　 ￣｀ヽ　　 　 ＼|｀||　|::/:::::::::::ﾉ
　　 　 　 　 ＼＿___/:＼|_／:::::::／|
　　　　　　　　　　　＼:::::::::::::／::::::|
　　　　　　　　　　　　 |￣￣::::::::::::|
"""

yaranai_smoke="""
　　 ／￣￣＼
　　　／　　 _ノ　　＼　　（ ;;;;(
　　　|　　　 （ ─）（─　　) ;;;;)
　　　|　　　 　 （__人__）　/;;／
.　　　|　　　　　　　　ﾉ　l;;,´
　　　 |　　　　　∩ ノ)━・'
　　／　　　　／ ＿ノ´
　 (.　 ＼ ／　.／ 　 │
　　＼　 “　／_＿_|　 |
.　　　 ＼／ ＿＿＿ /
"""


yaruo_pc ="""
　　　　　 ＿＿＿_
　 　 　 　 ／　　　　　＼
　　　　 ／　 　⌒　　⌒ ＼　　   
　　　／　 　 （●） 　（●） ＼
　 　 |　 　､"　ﾞ)（__人__）"　　）　　　 _＿＿＿＿＿＿＿＿＿_
　　　＼　 　 　 ｡｀ ⌒ﾟ:j´　,／　jﾞ~~| | |　　　　　　　　　　　　　|
＿＿／　　　　　　　　　　＼　 |_＿| | |　　　　　　　　　　　　　|
| |　/　　 ,　 　 　 　 　 　 　 ＼ｎ||　 | |　　　　　　　　　　　　　|
| | /　　 /　　　　　　　　　r.　 （ こ） | |　　　　　　　　　　　　　|
| | |　⌒ ーnｎｎ 　 　 　 　|＼ (⊆ｿ .|_|_＿＿＿＿_＿＿＿＿_|
￣ ＼＿_､("二）￣￣￣￣￣ｌ二二ｌ二二　 ＿|_|＿_|＿
"""

yaruo_pc2="""
　　　　　　　＿＿＿
　　　　　　　／　　　　　＼
　　　　　 ／　　 ＼ ,　, ／＼ 
　　　　／　 　 （●）　 （●） ＼
　　 　 |　　 u. 　 （__人__）　　　| 　　 　　._＿＿＿＿＿＿＿＿＿_
　 　 　 ＼　 　 　 ` ⌒ ´　　,／ｶﾞﾁｬ　　| |　　　　　　　　　　　　　|
　　　 　 /⌒ヽ　 　ー‐ 　　 ｨヽ　ｶﾞﾁｬ　.| |　　　　　　　　　　　　　|
　　　 　 |　　|　　　　 　 　 　|　＼ ｶﾞﾁｬ.| |　　　　　　　　　　　　　|
　ﾀﾝ.　　|　　|　　 　 　 i i| 　i＼,,c｀ヽ彡.| |　　　　　　　　　　　　　|
.　　ﾀﾝ　|　⌒￣￣r～ﾉｿｨ" | 　inﾙｿノﾉ|_|_＿＿＿＿_＿＿＿＿_|
　|＼￣￣　ー─‐─ｏｰ"o￣￣~´￣￣　　　　 ＿|_|＿_|＿
"""


yarume="""
　    　 　 ／）
　　　　   　／／／）￣｀ ｰ - ､
　　 　 　 ／,.=ﾞ''"／ : : : :｀ﾄ､: : :＼
　  　 　 i f　,.r='"-‐'つ/ l/: :ヽ.ﾊ ﾍ
　 　 　/　　　_,.-‐'~:/ゝﾉｲ ﾉ l/へ ! |
　   　,i　　　,二ﾆ⊃（●）　 （●）ｌ;小|
　　ﾉ　　　 ilﾞフ⊂⊃　､_,､_,　⊂⊃:::l
　,ｲ｢ﾄ､　　,!,!| |: : :| 　 （_.ノ　　丿Vﾄ、
/　iﾄヾヽ_/ｨ";ﾙlﾊレ 、 ,　 イﾉ{!;人:｀ヽ、
"""

yarume2="""
　　　　　　　 　 ,. :'´￣￣｀ ｰ - ､
　 　 　 　 　 ／: : : :／: : : :｀ﾄ､: : :＼
　　　　　　 ,': :∧〉/ l/ }:l:/l,: }　ヽ.ﾊ ﾍ
　　 　 　 　{: /:/ /ゝﾉｲ _ノ　'' ⌒.}_} ! |
　　　 　 　 |: ﾚ': :|: : {（● ） （● ）ｌ;小|
　　　　　　 |: i: :（|: : :|⌒,　 ゝ　⌒l ! l.!
　　　　　　 ﾊi : : |: : :|　　`ｰ=-'　丿Vﾄ、
　 　 　 　 / ;ﾙlﾊレVl＞ 、.__,　イﾉ{!;人:｀ヽ、
　　　　　/:⊂⌒ヽ/　　　　　　　 　ヽ /⌒つ}
　 　 　 ,': :,'　＼　ヽ　 /　　 　 ヽ　　　　/ｉ: :l
　　　　 ｉ: :l　 　 ＼_,,ノ　　　　　　|､＿ノ　l: :ｊ
"""

yarume3="""
　　　　 　 -‐ '´￣￣｀ヽ､
　　　／: :,／/; : :ﾄ､: ヽ: : ＼　 ?
　　 /: : :/l/ }:l:/l,:} ＼__＼ :
　　 {//ゝ､ﾉｲ ﾉlｿ､＿ |×`ｎｎ
　　 |l:/|,'（●）　 （●）}￣i,.|..| |^n
　　 |/:l:l⊃　､_,､_,　⊂⊃ !;.|.|..| |.|
　　 ,!ｉVﾍ、　 ゝ._） 　 |: : | ;|！ : :|
　／ ;ﾊレ!へ,､ __,　 イ: : :人　 :イ
/: : ;'. _r‐' {￣rj　　　{!ﾊl;ハ|　 │: :ヽ
: : ,' /　＼　　|ヽ.　 ／ }　 /|　 │ｉ: : l
: : l/　　i　＼ | ＿＿　ﾉ／ .|　 │l: : ｊ
"""

computer_mobile ="""
　＿＿＿＿＿_
_|0００OOO０00|_  
|__＿＿＿＿＿＿|   
｜||　ﾟ　 .。 ゜　。|    
｜||｡ﾟ∧＿∧ 。 |
｜||ﾟ.（。´∀｀）.゜;|
｜||｡（　　　゜）。 |　　　∧＿∧　＿＿_
｜||　|.　ﾟ|　｡|.　｡|　　 （　´∀｀）//　　/
｜||｡（＿_）＿）｡ |　　 /￣(つ__//＿_/
｜||＿＿＿＿＿|　　 | __￣{ニ=====|
{￣￣￣￣￣￣￣} 　ゝ＿|￣|￣￣￣|
|￣￣￣￣￣￣(((ニニ || |￣|￣￣￣|
"""

computer_pc ="""
　　　　　　　　　　　　 |￣￣￣|　 　 |￣￣￣|
　　　　　　　　　　　　 |　三三 |　 　 | 三三　|
　 　 　 　 　 |￣￣￣￣|三三 |　 　 | 三三|￣￣￣￣|
　　　　 　 |￣￣￣￣|　|三三 |　 　 | 三三|　|￣￣￣￣|　 l￣￣￣￣￣￣￣l＿
　　　 　 　|三三三三|　|三 |￣￣￣￣| 三|　|三三三三|　 |.|「「「「「「「「「「「「| |(.~＼
　　　 　 　|∥∥∥∥|　|三 |≫≫≪≪| 三|　|∥∥∥∥|　 |.|「「「「「「「「「「「「| | ＼(~＼
　　　 　 　|∥∥∥∥|　|三 | ＿　　＿ | 三|　|∥∥∥∥|　 |.|二二二二二二| | 　 .＼(~＼
　　　 　 　|∥∥∥∥|　|三 ||ｌ0ｌ| 　|ｌ0ｌ|| 三|　|∥∥∥∥|　 |.|llllllllllllllllllllllllllllllll| |＿＿_|＿__|＿＿＿
　　　 　 　|三三三三|　|三 ||ｌ0ｌ| 　|ｌ0ｌ|| 三|　|三三三三|　 |.|============| ||┌───┐ … |｜　 ＿＿＿＿_
　　　 　 　| ○。　 　 |　| 　 ||ｌ0ｌ| 　|ｌ0ｌ|| 　 |　| 　 　。○ |　 |.|llllllllllllllllllllllllllllllll| ||│ 　 　 　｜ 目 |｜　 ||￣￣￣|| |
　　　 　 　| LLLLLL |　| 　 ||ｌ0ｌ| 　|ｌ0ｌ|| 　 |　| LLLLLL |二))| ===========| ||｜ 　 　 　｜ 目 |｜　 ||＿＿＿|| |
　　　　 ∧＿∧　＿＿_　　　　　　　　　　　　　　　　　　　　　　　　　 　 　 　 　 |└───┘ Φ |□□||目∞◎|| |
　　　　（　´∀｀）//　　/　　　　　　　　　　　　　　　　　　　　　　　　　　　　 　 　|￣￣￣￣￣|　／∴¨θ∞ヽ／￣.|
　　　 ./￣(つ__//＿_/　　　　　　　　　　　　　　　　　　　　　　　　 　 　 　 　 　 |: 　 　 ⊂⊃ :| |￣￣￣￣￣|:　　　|
　　　 | __￣{ニ=====|　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　 ￣￣￣￣￣　￣￣￣￣￣￣￣￣
　 　 .ゝ＿|￣|￣￣￣|
(((ニニ || |￣|￣￣￣|
"""